version: '3.8'

services:
  bot:
    build: .
    container_name: madx-ticket
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: madx-ticket-db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}

volumes:
  mongodb_data:
